account.default-amount=500
account.transfer-commission=0.02
db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bank}
db.username=${DB_USER:postgres}
db.password=${DB_PASSWORD:root}
db.dialect=org.hibernate.dialect.PostgreSQLDialect

hibernate.hbm2ddl.auto=update
hibernate.show_sql=true
hibernate.format_sql=true
